title: The Hub
email: steve.wilson@digital.justice.gov.uk
description: >- # this means to ignore newlines until "baseurl:"
  The HMPPS Digital Hub prototyping kit
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

include:
  - _pages
  - _layouts
  - _includes

# Build settings
markdown: kramdown
# theme: minima
theme: govuk-jekyll-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - LICENSE
  - docker-compose.yml
  - README.md
