version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Install -g Gulp
          command: npm install gulp
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Prototype
          command: gulp build
