version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Install Gulp
          command: npm install -g gulp
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Copy gov assets into project
          command: gulp copyGovAssets
      - run:
          name: Build prototype
          command: gulp build
# Deploy test
  - deploy:
      command: |
        if [ "${CIRCLE_BRANCH}" == "master" ];
          then ./scripts/deploy-to-test.sh test;
        fi
